package br.ufal.ic.arq.ui.user;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.safari.SafariDriver;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class UserAddUITest {
    public static final String LOGIN_ADMIN = "admin";
    public static final String LOGIN_PASSWORD_ADMIN = "admin";
    public static final String USER_FIRST_NAME_ANTONIO = "antonio";
    public static final String USER_LAST_NAME_GERONCIO = "geroncio";
    public static final String USER_LOGIN_AGERONCIO = "ageroncio";
    public static final String USER_EMAIL_ANTONIO_SANTOS_MCZ_GMAIL_COM = "antonio.santos.mcz@gmail.com";
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Before
    public void setUp() {
        driver = new SafariDriver();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        //jdbcTemplate.execute("DELETE FROM jhi_user u WHERE u.login = '"+USER_LOGIN_AGERONCIO+"'");
    }

    @After
    public void tearDown() {
    driver.quit();
    }

    @Test
    public void add() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1280, 709));
        driver.findElement(By.cssSelector("#account-menu > span > span")).click();
        driver.findElement(By.cssSelector("#login > span")).click();
        driver.findElement(By.id("username")).sendKeys(LOGIN_ADMIN);
        driver.findElement(By.id("password")).sendKeys(LOGIN_PASSWORD_ADMIN);
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.cssSelector("#admin-menu > span > span")).click();
        driver.findElement(By.cssSelector(".show > li:nth-child(1) span")).click();
        driver.findElement(By.cssSelector(".float-right")).click();
        driver.findElement(By.name("login")).sendKeys(USER_LOGIN_AGERONCIO);
        driver.findElement(By.name("firstName")).sendKeys(USER_FIRST_NAME_ANTONIO);
        driver.findElement(By.name("lastName")).sendKeys(USER_LAST_NAME_GERONCIO);
        driver.findElement(By.name("email")).sendKeys(USER_EMAIL_ANTONIO_SANTOS_MCZ_GMAIL_COM);
        driver.findElement(By.id("langKey")).findElement(By.xpath("//option[. = 'Português (Brasil)']")).click();
        driver.findElement(By.cssSelector(".btn-primary > span")).click();
        js.executeScript("window.scrollTo(0,0)");



    }
}
